//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Books
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        public int PageId { get; set; }
        public Nullable<int> BookId { get; set; }
        public Nullable<int> PageNo { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    }
}
